import { ThemeProvider } from "@/context/ThemeContext";
import "./globals.css";
import { FontProvider } from "@/context/FontContext";

export const metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <FontProvider>
          <body className="flex flex-col justify-center">{children}</body>
        </FontProvider>
      </ThemeProvider>
    </html>
  );
}
